name: HuHoBotOnlineList
version: '${version}'
main: cn.huohuas001.huhobot.onlinelist.OnlineListPlugin
description: 通过 HuHoBot Addon API 生成可自定义底图的 Minecraft 在线玩家列表图片
authors:
  - RiegaLee
  - Shabby-666
api-version: '1.16'
load: POSTWORLD
depend:
  - HuHoBotPenguin
softdepend:
  - SkinsRestorer
commands:
  huhobotonlinelist:
    description: 生成在线列表本地测试预览或查看插件状态
    usage: /huhobotonlinelist [test <0-300> [页码] [名称模板]]
permissions:
  huhobotonlinelist.admin:
    description: 允许生成虚假玩家在线列表测试预览
    default: op
  huhobotonlinelist.priority:
    description: 在在线列表中作为管理员置顶显示
    default: op
